##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---

- name: calculate compute score
  calculate:
    metrics:
      ssl_rsa: "{{ ssl_rsa_metrics }}"
      ssl_aes: "{{ ssl_aes_metrics }}"
      dpi_throughput: "{{ dpi_metrics }}"
      intmem: "{{ intmem_metrics }}"
      floatmem: "{{ floatmem_metrics }}"
    spec:   "{{ qtip_resources }}/QPI/compute.yaml"
    dest: "{{ qtip_results }}/compute.json"
  register: qpi_result
  delegate_to: localhost
